apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatapp.fullname" . }}-secrets
  labels:
    app: {{ include "chatapp.name" . }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  scim-token: {{ .Values.scim.bearerToken | b64enc | quote }}
  encryption-key: {{ .Values.encryption.key | b64enc | quote }}
