apiVersion: v2
name: chatapp
version: 0.1.0
description: WebSocket Chat Application
type: application
appVersion: "1.0"
kubeVersion: ">=1.21.0-0"
maintainers:
  - name: ChatApp Maintainer
    email: maintainers@example.com
