# Generated by Django 4.2.22 on 2025-06-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatApp", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="legal_hold",
            field=models.BooleanField(
                default=False, help_text="Do not delete messages while enabled"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="retention_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Retention period override in days", null=True
            ),
        ),
    ]
