# Generated by Django 4.2.22 on 2025-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatApp", "0005_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("analyst", "Analyst"),
                ],
                default="analyst",
                max_length=10,
            ),
        ),
    ]
