# Generated by Django 4.2.22 on 2025-06-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatApp", "0006_add_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Two-factor auth secret",
                max_length=32,
            ),
        ),
    ]
