# Generated by Django 4.2.22 on 2025-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatApp", "0007_add_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
