# Generated by Django 4.2.22 on 2025-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatApp", "0008_audit_log_hash_chain"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=255, unique=True)),
                ("ttl_seconds", models.PositiveIntegerField()),
                ("override_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
